name: "Big Honkin' Magnets"
favicon: null
layout_spectrum: 0.43166970647871494
typography_spectrum: 0.8490699138492346
title: "Big Honkin' Magnets"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9948093837592751
  lightness: 0.1577963731251657
  saturation: 0.5948466248810291
  rhythmicContrast: 0.43424036260694265
purpose: []
