name: Big Honkin Magnets
favicon: null
layout_spectrum: 0.33474
typography_spectrum: 0.30482
title: Big Honkin Magnets
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#91908e'
    - '#d16e2d'
    - '#893837'
    - '#1e1916'
  brandStrength: 0.0625
  lightness: 0.1875
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
